services:
  app:
    build:
      context: .
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
    ports:
      - '3000:3000'

  db:
    image: postgres:17.2-alpine
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '54321:5432'
    environment:
      POSTGRES_DB: spincycle
      POSTGRES_USER: spincycle
      POSTGRES_PASSWORD: spincycle

  redis:
    image: redis:7-alpine3.17
    restart: unless-stopped
    volumes:
      - redisdata:/data
    ports:
      - '63791:6379'

volumes:
  pgdata:
  redisdata:
