# fly.toml app configuration file generated for spin-cycle-mono on 2025-01-12T10:53:42-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spin-cycle-mono'
primary_region = 'ord'

[build]

[deploy]
  release_command = "npm run db:migrate:run"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
